### ISSUE TITLE
Is it necessary to store a DB?

### ISSUE THREAD

**Issue by marlycormar** [pharmaR/risk_assessment#11]
I would like to open to discussion the idea of not including the DB in the repo. 

Downsides of having the DB as part of the repo:
- unintentionally commit the DB with user information,
- unnecessary extra file (we can always create the DB or use existing one when the app is ran), and
- the end user will most likely use a DB stored somewhere else.

**Comment by AARON-CLARK** [comment]
Hi @marlycormar, can you explain what the db file is/ does? Thanks!

**Comment by AARON-CLARK** [comment]
Just to follow up from an in-person conversation between @marlycormar, @MayaGans, @Robert-Krajcik today: we discussed how we should delete the DB file from our repo before pushing any PR's to github.

**Comment by Robert-Krajcik** [comment]
This appears to have been fixed with merging #19 Sunday
