### ISSUE TITLE
Updating to Shiny 1.6.0 breaks shinyWidgets::sliderTextInput()

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/risk_assessment#116]
When on Shiny v 1.6.0, the following text slider becomes unselectable and "crunched" aesthetically.

![image](https://user-images.githubusercontent.com/17878953/112651169-836e2c80-8e22-11eb-99f1-02dc50a85a36.png)

According to the shinyWidgets repo, sliderTextInput was broken when with recent shiny update
https://github.com/dreamRs/shinyWidgets/issues/342

After upgrading to latest package a shinyWidgets, the sliderTextInput issue goes away!

![image](https://user-images.githubusercontent.com/17878953/112650895-3f7b2780-8e22-11eb-8c5f-a2a42f58463a.png)

**Comment by Robert-Krajcik** [comment]
Thanks for finding this, @AARON-CLARK !
I'll update my shinywidgets now.l
