### ISSUE TITLE
Testing Metrics

### ISSUE THREAD

**Issue by MayaGans** [pharmaR/risk_assessment#12]
I tried looking at the testing metrics for several packages but this doesn't seem to work and only returns 

```
Metric is not applicable for this source of package
```

Is this a feature yet to be added? ....Where is the app calling `covr` (or maybe riskmetric should be doing that)?

**Comment by Robert-Krajcik** [comment]
Now when you select the "testing metrics" tab you get:
```{r, eval=FALSE}
Warning in .testLength(param = num, len = 1, arg = arg) :
  NAs introduced by coercion
Warning: Error in if: missing value where TRUE/FALSE needed
  99: .testInterval
  98: amAngularGauge
  95: func
  82: origRenderFunc
  81: output$test_coverage
   1: runApp
```

**Comment by marlycormar** [comment]
Hi @MayaGans, you are right. The code coverage metric hasn't been implemented in `riskmetric`. The app does rely on the output of `riskmetric`.

To see `riskmetric` in action, run the following code.
```
devtools::install_github("pharmaR/riskmetric")
View(pkg_ref("dplyr") %>%
    as_tibble() %>%
    pkg_assess() %>%
    pkg_score() %>%
    mutate(risk = summarize_scores(.)))
```

Notice that the column `covr_coverage` is `NA`.

There are still problems with the code that saves/loads the test-coverage-related-info into the db, but I'll create separate issues to fix them.

**Comment by marlycormar** [comment]
Hi @MayaGans, I'll close this issue in favor of https://github.com/pharmaR/risk_assessment/issues/45. Feel free to reopen it if you think we should keep our discussion here.
