### ISSUE TITLE
Launch Page should limit roles

### ISSUE THREAD

**Issue by ghost** [pharmaR/risk_assessment#13]
Maybe use a drop-down list, or read a .csv to match the user id.
Or something else?

**Comment by marlycormar** [comment]
Hi @Robert-Krajcik, as we discussed last time let us hold off on working on this. But it is good to have this issue open to discuss our ideas.

**Comment by marlycormar** [comment]
This issue is related to https://github.com/pharmaR/risk_assessment/issues/14.

**Comment by marlycormar** [comment]
Limiting roles is part of setting authentication for the app (issue #3). I'll mark this issue as duplicate, so we can keep our brainstorming organized on the same issue.
