### ISSUE TITLE
Creating an audit trail when updating the weights/risk

### ISSUE THREAD

**Issue by marlycormar** [pharmaR/risk_assessment#134]
- Save information (loggit) pertinent to the admin changing the weights/risk.
- Leave a comment in every tab (i.e., community usage, maintenance metrics, overall comments).

**Comment by Robert-Krajcik** [comment]
Yes this has been updated.
![image](https://user-images.githubusercontent.com/75215958/149025864-a49c4eac-8517-4495-9842-65ff42323576.png)
