### ISSUE TITLE
Submit Decision action button should be restricted

### ISSUE THREAD

**Issue by ghost** [pharmaR/risk_assessment#14]
and not visible or greyed out for anyone other than the decision maker

**Comment by Robert-Krajcik** [comment]
In sidebar.R we could add

```{r}
observeEvent(input$role, {
  if (input$role == "DecisionMaker") {
    enable("submit_decision")
  } else {
    disable("submit_decision")
  }
},ignoreInit = TRUE)  
```
How we assign roles to userids has not yet been decided.
Any thoughts on this, @AARON-CLARK or @MayaGans

**Comment by marlycormar** [comment]
> Submit Decision action button should be restricted

Definitely @Robert-Krajcik. I envision this tied up to the company's internal authentication system. This way guarantees that we can extract the role from the user's information and we don't have to require passwords.

Another way would be to set roles manually in some way. You suggested one here https://github.com/pharmaR/risk_assessment/issues/13.

**Comment by marlycormar** [comment]
Restricting the submit decision to certain roles is part of setting authentication for the app (issue #3). I'll mark this issue as duplicate, so we can keep our brainstorming organized on the same issue.
