### ISSUE TITLE
`rintrojs` help box says "Close" instead of "X"

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/risk_assessment#143]
Hi, wondering everyone's thoughts on the following: The `rintrojs` help modal that shifts across the screens has a large bold "Close" word that serves as a button to close the modal. I would argue that the traditional "x" would be more appropriate since it is the industry standard for closing windows. It's not obvious that "Close" is even a button... kind of like a norman door. It's easy to switch, just have to remove [this ](https://github.com/pharmaR/risk_assessment/blob/34fafe42e400c921ebf2badc8548a3f68752fd58/Server/uploadpackage.R#L48) line of code. I'd be happy to open a PR, but don't want to do so if anyone has strong opinions about it?

![image](https://user-images.githubusercontent.com/17878953/142253136-8447779a-4f51-442d-8146-79a5b2c10163.png)

![image](https://user-images.githubusercontent.com/17878953/142253217-36071e34-8c9e-4df9-9ab2-ebae11d0775e.png)

**Comment by marlycormar** [comment]
Hi @AARON-CLARK, I also think that **x** is better than **Close**. 

Since the tweak to accomplish this is so simple, I think it a good idea to go ahead with the switch.
