### ISSUE TITLE
Change wording when asking for keyring

### ISSUE THREAD

**Issue by marlycormar** [pharmaR/risk_assessment#148]
The prompt to enter keyring is "Enter keyring password". This prompt may suggest that the keyring is an existing password. We should change the wording to something like (this is just a blunt suggestion): 

"Please create a keyring password and stored it in a safe location. This keyring can be used to retrieve user passwords from the database."

What do you guys think? @AARON-CLARK @Robert-Krajcik

**Comment by Robert-Krajcik** [comment]
How about
"Please create a keyring password"?
There's limited space in `askForPassword()`
`rstudioapi::askForPassword("Please create a keyring pasword"))`

**Comment by marlycormar** [comment]
Addressed by #150
