### ISSUE TITLE
i (?) - button next to Assessment Criteria

### ISSUE THREAD

**Issue by MayaGans** [pharmaR/risk_assessment#15]
There's an i icon next to Assessment Criteria on the top left of the application. On hover the i produces a question mark but clicking the i doesn't result in anything. Is this intentional?

**Comment by marlycormar** [comment]
Hi @MayaGans, it is intentional, although I don't agree with the stylistic choice. It is meant to represent that the 'Assessment Criteria' button is a 'help' button.

**Comment by marlycormar** [comment]
@MayaGans what do you think if we remove completely (i) and change the label of the button to something like: 'About Assessment Criteria'?

**Comment by MayaGans** [comment]
I like that, I tried your suggestion and also 'Read Assessment Criteria' as below, but both are kind of long titles for a button. I think we can just write "Assessment Criteria" honestly or maybe "Read details", it was just confusing having the icon next to a button.

<img width="1189" alt="Screen Shot 2020-09-09 at 7 24 29 AM" src="https://user-images.githubusercontent.com/6053906/92611371-91d16e00-f26d-11ea-87e8-8c51ef9b6545.png">

Another entirely different option I'd be happy to explore is to _just_ have the [i] icon and on hover show "Read Assessment Criteria"

Have any strong opinions @marlycormar ?

**Comment by MayaGans** [comment]
# Button 
<img width="684" alt="Screen Shot 2020-09-09 at 7 44 56 AM" src="https://user-images.githubusercontent.com/6053906/92613994-669c4e00-f270-11ea-8546-f27ccdc70f60.png">

# On Hover
<img width="659" alt="Screen Shot 2020-09-09 at 7 45 02 AM" src="https://user-images.githubusercontent.com/6053906/92613984-63a15d80-f270-11ea-8ff4-a131f08bae4f.png">

**Comment by MayaGans** [comment]
Stylized on hover to fit more with the app - I can submit a PR if you like it!

<img width="179" alt="Screen Shot 2020-09-09 at 7 51 17 AM" src="https://user-images.githubusercontent.com/6053906/92614817-520c8580-f271-11ea-928d-838a84ffcf1d.png">

**Comment by AARON-CLARK** [comment]
@MayaGans, look awesome!
