### ISSUE TITLE
Modularize UI and Server code?

### ISSUE THREAD

**Issue by MayaGans** [pharmaR/risk_assessment#16]
This is a stylistic question/proposal: 

going through the source code it looks like each component within the application has a matching file name within the `UI` and `Server` folders. I don't think it would be difficult to convert these files to shiny modules to be conditionally rendered within app.R but this is assuming we'd want to adopt a shiny module framework.

Thoughts?

**Comment by MayaGans** [comment]
Related - I'm still solidifying my mental model of the package but it seems from my perfunctory understanding that `cum_report.R` `mm_report`, and `tm_report` which are all called within `report_preview` seem to repeat a lot of the code found in `communityusage_metrics`, `maintenance_metrics`, and `testing_metrics` respectively.

Unless my mental model isn't correct I think we can reduce this seeming redundancy if we just call the modules once in their tabs, and again in the report file -- thoughts?

**Comment by MayaGans** [comment]
Looks like there's also some code redundancy in the ability to leave comments on every tab, if we do want to go this module route maybe we create a `comments` module that can be called within each tab?

**Comment by AARON-CLARK** [comment]
> 
> I don't think it would be difficult to convert these files to shiny modules to be conditionally rendered within app.R but this is assuming we'd want to adopt a shiny module framework.
> 
> Thoughts?

I'm kind of *indifferent*. We could use shiny modules, but what what's the payout / value add?

**Whiteboarding:**
Pros: 
* Using shiny modules is the industry standard? Correct? Or are tidyModules fighting for that position now?
* It would help with any namespace collisions

Cons:
* It's extra work

**Comment by MayaGans** [comment]
Thanks for your feedback @AARON-CLARK! I was thinking it'd help reduce code redundancy (we'd only need one comment module rather than repeating the code in every tab, and wouldn't need to repeat the code in the report tab) but you're totally right not trying to create extra work just because we can, was just curious to get the groups thoughts since I saw a lot of recycled code

**Comment by AARON-CLARK** [comment]
> Thanks for your feedback @AARON-CLARK! I was thinking it'd help reduce code redundancy (we'd only need one comment module rather than repeating the code in every tab, and wouldn't need to repeat the code in the report tab) ...

@MayaGans, sorry, I should clarify. When I said, "I'm indifferent" I was referring to your first question/post on whether or not we use shiny modules vs leave the modules as-is (just an R file that get's sourced).

Either way, I am on board with reducing redundancy. What's interesting is the reportpreview.R on the server side seems to call the code in a shiny module-y way: 

![image](https://user-images.githubusercontent.com/17878953/90016546-27caa680-dc78-11ea-9d33-e7bbb7fa30b7.png)

But then, `maintenance_metrics.R` & `mm_report.R` are truly redundant which makes my skin crawl. It looks like the only difference might be that the `mm_report.R` file doesn't have the input called "submit_mm_comment" which makes sense since it's the input that saves a comment to the db.

Looking deeper into the differences between these two mm files, it looks like all the outputs have the same names, but in the `mm_report.R` file, they just have a "1" suffix appended to avoid namespace collisions! For example, `output$mm_commented` becomes `output$mm_commented1`.

Soooo, by the end of this post, I think I'm no longer indifferent. I'd love to clean this up with SHINY modules.

**Comment by Robert-Krajcik** [comment]
I have come up with a function called `upd_comments` which handles comments from maintenance_metrics, communityusage_metrics and testing_metrics.   Just pass the comment and it figures out the rest.
Hopefully separating this out will make combining testing_metrics with tm_report, and so on easier.
Right now there's a bit of code left in each of the modules, but maybe I could come up with one observeEvent that looks for any of maintentance_metrics, communityusage_metrics and testing_metrics.

```{r}
observeEvent(input$submit_mm_comment, {
  upd_comments(input$mm_comment)
}, ignoreInit = TRUE)  
```

```{r, eval=FALSE}
upd_comments <- function(cmnt) {
  
  # extract the characters between $ and _
  cm_type <- str_extract(deparse(substitute(cmnt)), "(?<=\\$)([a-z]+)(?=_)")
  
  if (trimws(cmnt) != "") {
    db_ins(
      paste0(
        "INSERT INTO Comments values('",
        input$select_pack,
        "',",
        "'",
        values$name,
        "'," ,
        "'",
        values$role,
        "',",
        "'",
        cmnt,
        "',",
        "'",
        cm_type,
        "',",
        "'",
        TimeStamp(),
        "'"  ,
        ")"
      )
    )
    zz_submitted <- glue::glue({cm_type},"_comment_submitted")
    values$zz_submitted <- "yes"
    txt <- glue::glue({cm_type},"_comment")
    updateTextAreaInput(session, txt , value = "")
  }
  
} 
```

**Comment by Robert-Krajcik** [comment]
OK simplified a bit more.  I put this in the App.R

```{r}
  toListen <- reactive({
    list(input$submit_tm_comment,input$submit_mm_comment, input$submit_cum_comment)
  })
  observeEvent(toListen(), {
    req(input$select_pack != "")

    values$mm_comment_submitted <- "no"
    values$tm_comment_submitted <- "no"
    values$cum_comment_submitted <- "no"

    if (!is.null(input$submit_mm_comment)  && input$submit_mm_comment  > 0) upd_comments(input$mm_comment)
    if (!is.null(input$submit_tm_comment)  && input$submit_tm_comment  > 0) upd_comments(input$tm_comment)
    if (!is.null(input$submit_cum_comment) && input$submit_cum_comment > 0) upd_comments(input$cum_comment)

  }, ignoreInit = TRUE)
```

**Comment by marlycormar** [comment]
We will refer back to this issue in another one encompassing all potential new features. Once we are ready to work on this issue, it will be reopened.
