### ISSUE TITLE
`metric_cum_Info_upload_to_DB()` is broken

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/risk_assessment#163]
Hi all,

The Community Usage plotly is missing pertinent info. I pulled up `dplyr` and compared it against their [documentation site](https://github.com/tidyverse/dplyr/releases?page=1) and confirm that (1) Jan 2021 is missing from the plot, (2) all the version releases aren't getting plotted any more, and (3) the **Version Maturity** infoBox shouldn't be `NA`!

![image](https://user-images.githubusercontent.com/17878953/150548107-710a0a91-652b-41da-a64b-5f98bbea4e83.png)

I've traced the issue back to  `metric_cum_Info_upload_to_DB()` function which is responsible for generating & inserting community usage metrics into the database. To be specific, if you run this:

```
metric_cum_Info_upload_to_DB(package_name = "dplyr")
chk <- db_fun("SELECT * FROM CommunityUsageMetrics WHERE cum_id ='dplyr'")
```
And inspect `chk`, you get the below data: 

![image](https://user-images.githubusercontent.com/17878953/150546947-62dce26b-b00f-4711-a364-9b12e46b4b67.png)

First, I know why the "same month last year" row (in this case, that's Jan 2021, since the query was run Jan 2022) is missing. I apologize, but I think I missed it when I was revamping the code to go back 2 years in time instead of one year. Basically, we just need to remove/ comment out [this line](https://github.com/pharmaR/risk_assessment/blob/43bb66fa4b8cc7b542b541c0aa9280c504e9a555/Modules/dbupload.R#L219) of code. 

Secondly, two columns above are completely `NA`! I've walked through the function's code line-by-line (a few times) inside the `tryCatch` and when I do so, the code seems to produce the correct result (as seen below) so I'm not entirely sure why it doesn't work when calling `metric_cum_Info_upload_to_DB("dplyr)`. @marlycormar or @Robert-Krajcik, could one or both of you check it out?

![image](https://user-images.githubusercontent.com/17878953/150552895-ba1e4dc0-3eeb-439d-9770-19a7b6fd12b8.png)

**Some extra notes:**
1. Ignore the **position** column values... I was playing with something. You may have different values and it doesn't really matter. We don't use this column for anything in the app or the plot.

2. I'm not sure why [this line](https://github.com/pharmaR/risk_assessment/blob/43bb66fa4b8cc7b542b541c0aa9280c504e9a555/Modules/dbupload.R#L242) exists. If it remains, it causes the following error once you get to [this line](https://github.com/pharmaR/risk_assessment/blob/43bb66fa4b8cc7b542b541c0aa9280c504e9a555/Modules/dbupload.R#L287) of code (below). If you comment it out, everything plays nicely.

![image](https://user-images.githubusercontent.com/17878953/150549508-bc1664aa-89ae-4a7a-8cf0-dfcbeb22223a.png)

3. If you run the loop that starts [here](https://github.com/pharmaR/risk_assessment/blob/43bb66fa4b8cc7b542b541c0aa9280c504e9a555/Modules/dbupload.R#L246), you'll eventually get the following error: 

![image](https://user-images.githubusercontent.com/17878953/150550796-c11e5d3b-208b-480e-86cf-c95bd0fea86e.png)

So perhaps we add something like that checks if `pkg_text_v1` isn't empty. In dplyr's case, after about 3 loops, the `pkg_text_v1` value was:

![image](https://user-images.githubusercontent.com/17878953/150551067-2788c9e2-47ff-40a7-94fa-d91405f3a6a0.png)

**Comment by Robert-Krajcik** [comment]
Hi @AARON-CLARK and @marlycormar 
I'm surprised the code for metric_cum_Info_upload_to_DB works at all.  What a mess!

If you remove the trycatch() you will see errors like you did above.

There is an easier way to do this.
```{r, eval=TRUE}
package_name <- "dplyr"
library(versions)
versn_data <- versions::available.versions(package_name)
head(versn_data)
```
I'm going to spend some on a replacement to this convoluted function.
