### ISSUE TITLE
Add back admin view

### ISSUE THREAD

**Issue by marlycormar** [pharmaR/risk_assessment#167]
Add back the admin view that allows to add/delete users (shiny manager). Create a dedicated tab for this.

**Comment by Robert-Krajcik** [comment]
This seems to work:

```{r, eval=FALSE}
            tabPanel(
              id = "admin_mode_id",
              title = "Administrator mode",
              # only using a div seems to work here
              div(id = "admin_mode",
              shinymanager:::admin_ui(id="admin")  )
            )
```
and then
`    if (user$role == "user") shinyjs::hide("admin_mode") `
to hide the admin functions from users
