### ISSUE TITLE
Default report name

### ISSUE THREAD

**Issue by andyofsmeg** [pharmaR/risk_assessment#2]
The reports all default to the same name, 'Report.html'.  Ideally the default name should contain the package name.  For example, '[pkg_name]_[pkg_version]_risk_assessment'.

**Comment by marlycormar** [comment]
Hi @AARON-CLARK, can we close this issue?

**Comment by AARON-CLARK** [comment]
> Hi @AARON-CLARK, can we close this issue?

Hi @marlycormar, this issue is closed when #10 is merged!
