### ISSUE TITLE
Improve x-axis of the downloads plot on the docx report 

### ISSUE THREAD

**Issue by marlycormar** [pharmaR/risk_assessment#212]

**Comment by Robert-Krajcik** [comment]
What would you like improved here, @marlycormar ?
![image](https://user-images.githubusercontent.com/75215958/158383226-7a356ba0-9522-4c7a-9220-358fe518611d.png)

**Comment by marlycormar** [comment]
On my end, the x-axis can't be read (overlapping text), but let me clean the session and try again.

**Comment by Robert-Krajcik** [comment]
#230 fixes this.  Closing this issue.
