### ISSUE TITLE
Database Tab

### ISSUE THREAD

**Issue by Jeff-Thompson12** [pharmaR/risk_assessment#223]
Do you all receive this error when accessing the Database Overview tab?
![image](https://user-images.githubusercontent.com/85879620/159543660-5b825cdd-a7b5-4f03-8ba5-6701ce509660.png)

I thought this was getting addressed in one of the several open PRs, but those PRs have been merged and the error is still there.

**Comment by AARON-CLARK** [comment]
@Jeff-Thompson12, nope! Everything looks peachy for me (see below). What version of the `DT` package are you running? I'm on on `v0.18`. Looks like the current version `v0.21` released 24 days ago.

![image](https://user-images.githubusercontent.com/17878953/159555709-88481071-a7ef-49ec-a4be-54806b125845.png)

**Comment by Jeff-Thompson12** [comment]
I am using the current version `v0.21`.

**Comment by AARON-CLARK** [comment]
closed with #225
