### ISSUE TITLE
Connect to a remote db?

### ISSUE THREAD

**Issue by Robert-Krajcik** [pharmaR/risk_assessment#25]
Apparently yes, but **not** with SQLite
The good news is that MySQL is very similar to SQLite

Blog from Dean Attali: https://shiny.rstudio.com/articles/persistent-data-storage.html

**Comment by marlycormar** [comment]
Hi @Robert-Krajcik, as per our discussion last time, we will stay with SQLite and create vignette explaining how to connect to a remote MySQL db.
