### ISSUE TITLE
Report doesn't contain risk score

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/risk_assessment#264]
Correct me if I'm wrong - but I downloaded this from the beta version of the app available on shinyapps.io and the riskmetric score is nowhere to be found? It should be displayed very prominently in this document.
[RiskAssessment-Report-2022-09-21_20-18-36.zip](https://github.com/pharmaR/risk_assessment/files/9625778/RiskAssessment-Report-2022-09-21_20-18-36.zip)

**Comment by imran3004** [comment]
PR #292 created.

**Comment by imran3004** [comment]
New PR #298 created to avoid issues with whitespaces.

**Comment by imran3004** [comment]
PR merged into dev branch.
