### ISSUE TITLE
return code from dbExecute ?

### ISSUE THREAD

**Issue by Robert-Krajcik** [pharmaR/risk_assessment#30]
From: https://rdrr.io/cran/DBI/man/dbExecute.html

`dbExecute()` always returns a scalar numeric that specifies the number of rows affected by the
statement. An error is raised when issuing a statement over a closed or invalid connection, if the
syntax of the statement is invalid, or if the statement is not a non-NA string.

Example:
```{r}
con <- dbConnect(RSQLite::SQLite(), ":memory:")

dbWriteTable(con, "cars", head(cars, 3))
dbReadTable(con, "cars")   # there are 3 rows
rc <- dbExecute(
  con,
  "INSERT INTO cars (speed, dist) VALUES (1, 1), (2, 2), (3, 3)"
)
print(paste("rc was",rc))
# [1] "rc was 3"
dbReadTable(con, "cars")   # there are now 6 rows
  speed dist
dbDisconnect(con)
```
So there's no "return code" per se

**Comment by marlycormar** [comment]
Hi @Robert-Krajcik, what is your question?

**Comment by Robert-Krajcik** [comment]
I was trying to figure out what gets returned from a dbExecute call.
It's either the number of rows affected or an error message.
Closing this issue.
