### ISSUE TITLE
File cum_report.R repeats code from other tabs

### ISSUE THREAD

**Issue by marlycormar** [pharmaR/risk_assessment#32]
As pointed out by @MayaGans, the files `cum_report.R` (inside `UI` and `Server`) repeat code from other tabs, including `communityusage_metrics.R`. Ideally, we should have modules (or even functions) that we can reuse as needed throughout the app.

It is not hard to find where the duplication occurs, e.g.,  the variables are named `no_of_downloads` vs `no_of_downloads1`.

**Comment by Robert-Krajcik** [comment]
Assuming we move the comment handling to its own area, the only thing different is the output areas.

Here's and idea I had.  And this code works. 
First we observe for **either** input$tabs value

```{r, eval=FALSE}
# 1. Observe to load the columns from DB into reactive values.
observe({
  req(input$select_pack)
  if (input$tabs %in% c("cum_tab_value","reportPreview_tab_value")) {
    if (input$select_pack != "Select") {
```
and then create a list of reactive variables and wrap the render outputs inside an observeEvent()
```{r, eval=FALSE}
out_cm <- reactive({
  req(input$select_pack)
  if (input$tabs == "reportPreview_tab_value") {
    return(list("time_since_first_release1","time_since_version_release1", "no_of_downloads1","cum_commented1")) }
  else {
    return(list("time_since_first_release", "time_since_version_release",  "no_of_downloads", "cum_commented"))
  }
})

observeEvent(input$tabs, {
  req(out_cm())
  req(input$tabs %in% c("cum_tab_value","reportPreview_tab_value"))

  # output$time_since_first_release <- renderInfoBox({
  output[[out_cm()[[1]]]] <- renderInfoBox({

...   # lines of code omitted ...

  # End of the Render Output's'.
},ignoreInit = TRUE)
```
Any thoughts about this, @marlycormar or @MayaGans  or @AARON-CLARK ???

**Comment by marlycormar** [comment]
This issue is fixed on the dev branch.
