### ISSUE TITLE
File tm_report.R repeats code from other tabs

### ISSUE THREAD

**Issue by marlycormar** [pharmaR/risk_assessment#34]
Similar to issues #32, #33.

**Comment by Robert-Krajcik** [comment]
Just ran a diffr on testing_metrics.R versus tm_report.R
and with the exception of
`# Observe event for submit button to submit the comments for testing metrics.`
at the bottom of testing_metrics.R
The code is essentially the same.

**Comment by marlycormar** [comment]
This issue is fixed on the dev branch.
