### ISSUE TITLE
Adding comment results in warning message

### ISSUE THREAD

**Issue by Robert-Krajcik** [pharmaR/risk_assessment#35]
`Warning in result_fetch(res@ptr, n = n) :
  SQL statements must be issued with dbExecute() or dbSendStatement() instead of dbGetQuery() or dbSendQuery().`

In sidebar.R, function `db_fun()` needs to be replaced with `db_ins()`

**Comment by marlycormar** [comment]
The warning message also appears whenever a comment a submitted. The option to submit a comment appear on the following tabs:

- [ ] Report Review
- [ ] Maintenance Metrics 
- [ ] Community Usage Metrics
- [ ] Testing Metrics

**Comment by Robert-Krajcik** [comment]
The others will be fixed with #47 move comments handling out of _metrics

**Comment by marlycormar** [comment]
Issue is now fixed.
