### ISSUE TITLE
Using SQLite command line

### ISSUE THREAD

**Issue by ghost** [pharmaR/risk_assessment#40]
- Take a look at https://www.sqlitetutorial.net/download-install-sqlite/
- Download sqlite-tools-win32-x86-3330000.zip
- Unzip to C:\sqlite -- No IT support needed.
- Look at https://www.sqlitetutorial.net/sqlite-commands
- Go to command line
- cd C:\sqlite and type: sqlite3

showing some commands below
Note forward-slashes are used when opening the database

.open "C:/Users/rkrajcik/OneDrive - Biogen/Documents/R/RiskAssessment/risk_assessment-master/database.sqlite"
Try clicking on the image to see it better.

![image](https://user-images.githubusercontent.com/62262182/92246511-daff7780-ee93-11ea-9bb7-56a05204cd4f.png)

**Comment by marlycormar** [comment]
Create a wiki page out of this issue.

**Comment by marlycormar** [comment]
We will refer back to this issue in another one encompassing all potential new features. Once we are ready to work on this issue, it will be reopened.
