### ISSUE TITLE
Make app more portable

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/risk_assessment#48]
When @Robert-Krajcik & I opened this app for use, we had some package version conflicts which halted it from running locally on our machines. I'm wondering if this project would be more portable to future uses if it was packaged up in a container, as discussed in a recent R Medicine talk (see link below) for ultimate reproducibility. Thoughts?

https://github.com/vincentmajor/reproducible_RStudio_projects

**Comment by marlycormar** [comment]
I think this may be good idea. An alternative is to make the app a package.

I am not sure of all the tradeoffs between dockerizing the app vs putting it in a package but here is one: 
need docker installed vs need RStudio/rR installed with the required packages

**Comment by AARON-CLARK** [comment]
Update: the team the created packrat have created a new successor package called `renv` that may pose a better solution to our portability problem. From my current understanding, the `renv` package would allow us to create/build a json file with specific versions of packages used to build this app. So, whenever our code is pulled down by a developer, each programmer should be able to develop in an identical R environment as us (based on the specifications in this json file).

Here is an [intro](https://rstudio.github.io/renv/articles/renv.html) to the `renv` package

**Comment by marlycormar** [comment]
We will refer back to this issue in another one encompassing all potential new features. Once we are ready to work on this issue, it will be reopened.
