### ISSUE TITLE
Packages dashboard & multiple downloads

### ISSUE THREAD

**Issue by marlycormar** [pharmaR/risk_assessment#51]
Multiple downloads reports & packages dashboard
- [x] Create a dashboard showing all packages on the db.
- [x] Allow selection of packages to download multiple reports.

(issue follows from discussion here https://github.com/pharmaR/risk_assessment/issues/1)

**Comment by AARON-CLARK** [comment]
On 9/14/20, we discussed some ideas of what might live on a "Packages Dashboard". Some ideas discussed included:
* how this may be a good place where users can highlight/ elevate a certain package that needs attention from others in the  organization ... soliciting more feedback / more comments
* displaying latest comment activity submitted to the database for any given package
* Displaying the top/bottom 10 rated packages that exist in the database, etc

Despite this initial brainstorm, we thought it was a good idea to throw all the packages (that exist in the database) into a table and at the very minimum, allow users to select multiple rows for download.

**Comment by AARON-CLARK** [comment]
On 9/21, we discussed making the table look more select-able with embedded checkboxes and/or changing the cursor to a hand. In addition, moving this table to a separate tab on the right-justified on the screen. Potentially the user will select a tab or toolbox icon.
