### ISSUE TITLE
Improve UI for the Upload Package tab

### ISSUE THREAD

**Issue by marlycormar** [pharmaR/risk_assessment#6]

**Comment by MayaGans** [comment]
What were you envisioning for this? I'd be happy to take this one!

**Comment by marlycormar** [comment]
Great @MayaGans! There is little going on this tab, so just accommodating the items on it (as you see fit) will work.

Note that the options to download multiple reports (temporarily) appear on this tab but we plan to move them to another one (more about this here https://github.com/pharmaR/risk_assessment/issues/1).
