### ISSUE TITLE
Download-all-reports section doesn't update

### ISSUE THREAD

**Issue by marlycormar** [pharmaR/risk_assessment#60]
The section on downloading all reports doesn't update when another CSV file is uploaded.

#### How to reproduce the issue
1. Run the app.
2. Upload a CSV with a package not in the db.
3. Repeat step 2.

**Comment by AARON-CLARK** [comment]
Hi @marlycormar, it looks like the multi-report download is in working order. It just downloads report(s) for whatever is displayed in the table of uploaded packages. I created PR #61 to update that table whenever a file is uploaded. Thanks and good catch!

Fixed via #61
