### ISSUE TITLE
Make "Back" button more obvious on 'History of Reviewed Packages' screen

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/risk_assessment#68]
I was having trouble attempting (upon uncommenting [this line](https://github.com/pharmaR/risk_assessment/blob/eb3c5d8ac4187b67c41adc4cac90a6a7c0fa8dd4/UI/db_dash_screen.R#L18) of code) to left justify the icon on the actionButton **while also** expanding the size using "fa-2x", but now it seems to work! My mistake! Although it's not center justified vertically.

![image](https://user-images.githubusercontent.com/17878953/94479854-63c3b780-01a3-11eb-9f3f-e8759dcfa0a7.png)

![image](https://user-images.githubusercontent.com/17878953/94479920-7f2ec280-01a3-11eb-9a19-0d3a4fde7f82.png)

**Comment by MayaGans** [comment]
@AARON-CLARK did you fix this? I just uncommented out the code and it looks great....
<img width="566" alt="Screen Shot 2020-10-19 at 1 32 58 PM" src="https://user-images.githubusercontent.com/6053906/96508561-a4957600-120f-11eb-9329-06d7dcabd4ee.png">

**Comment by AARON-CLARK** [comment]
> @AARON-CLARK did you fix this? I just uncommented out the code and it looks great....

It work's fine as is. But if you add in the `class = "fa-2x"` argument above, it get's a little off center. I think it looks fine though if you do?

**Comment by MayaGans** [comment]
I this it's fine with the smaller arrow? 🤷 

That said if we want to center it we can add in line styling to the strong tag:

```
actionButton("back2dash", strong(style="position:relative;bottom:5px;", "Return to Package Dashboard"),
                        icon = icon("arrow-circle-left", class="fa-2x")
                       )
```
