### ISSUE TITLE
Update x-axis on `Number of Downloads` plot

### ISSUE THREAD

**Issue by AARON-CLARK** [pharmaR/risk_assessment#74]
I’ve found a solution that addresses our need for a line plot that operates more like timeline plot (ie allows for panning, etc). It appears plotly has those functionalities built-in! Please take a look and play with the widget on this page, which includes the code to reproduce. I also like how we can add buttons to the at the top for common timespans (like 1yr, 2yr, etc).
 
https://plotly.com/r/range-slider/

Currently, the plot looks like [this](https://github.com/pharmaR/riskmetric/issues/168#issue-717347723).

**Comment by marlycormar** [comment]
Hey @AARON-CLARK, it seems that this plot may solve our issue. Is it possible to add vertical bars or some indication of particular package releases? Something similar to what we have:

<img width="600" alt="Screen Shot 2020-11-30 at 6 17 27 AM" src="https://user-images.githubusercontent.com/8559654/100603921-cc2e3280-32d3-11eb-8745-4d9fc22402b9.png">
