### ISSUE TITLE
Upload/Save of a single package can take over 10s

### ISSUE THREAD

**Issue by ghost** [pharmaR/risk_assessment#76]
Going back to branch master, deleting the database and loading the single dplyr package, I get:
`Time difference of 11.43519 secs`

Switch back to branch fix_versioningII, deleting the database and loading the same dplyr package
`Time difference of 8.961269 secs`
doing it again (there might be some internet delay time in here)
`Time difference of 7.695863 secs`

If I comment out these two functions:
```{r, eval=FALSE}
          # metric_mm_tm_Info_upload_to_DB(new_package,new_version)
          # metric_cum_Info_upload_to_DB(new_package,new_version)
```
I can get:  `Time difference of 0.165879 secs`
So clearly this is where the majority of time is being spent.

Suggest using the R profiler (Rprof) to study where the time is actually spent
and figure out what if anything we can do to reduce the elapsed times.

**Comment by marlycormar** [comment]
The `profvis` package may also shed some light into which processes are slowing down the app.

```
library(shiny)
library(profvis)

profvis({
  runApp("./")
})
```

**Comment by marlycormar** [comment]
We improved the time as much as we could.
