### ISSUE TITLE
Warning messages issued from community usage metrics tab

### ISSUE THREAD

**Issue by Robert-Krajcik** [pharmaR/risk_assessment#96]
on branch master

```{r, eval=FALSE}
Warning: `arrange_()` is deprecated as of dplyr 0.7.0.
Please use `arrange()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.
Warning: `group_by_()` is deprecated as of dplyr 0.7.0.
Please use `group_by()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.
```

**Comment by Robert-Krajcik** [comment]
Definitely coming out of plotly
```{r}
library(dplyr)
library(plotly)
df <- data.frame(
  a = rnorm(5, 50, 1), 
  b = letters[1:5], 
  stringsAsFactors = FALSE
)

plot_ly(df, x = ~a, y = ~b, color = ~b)
```
No trace type specified:
  Based on info supplied, a 'bar' trace seems appropriate.
  Read more about this trace type -> https://plot.ly/r/reference/#bar
Warning message:
`arrange_()` is deprecated as of dplyr 0.7.0.
Please use `arrange()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated.

**Comment by Robert-Krajcik** [comment]
Just installed the latest version of plotly (4.9.3) published 10Jan2021 
FYI @AARON-CLARK and @marlycormar, 
I was able to confirm that this issue goes away with the latest release of plotly.

Closing this out

**Comment by AARON-CLARK** [comment]
Good find @Robert-Krajcik
